title: Jimmy Mai
logo: /assets/headshot-circle.jpg
description: Data Science Enthusiast Seeking Full-Time Employment | MS Business Analytics Graduate @ UT Dallas
show_downloads: true
theme: jekyll-theme-minimal
