title: Jimmy Mai
#logo: /assets/img/headshot_circle.png
#description: Data Science Enthusiast Seeking An Internship| MS Business Analytics Student @ UT Dallas
show_downloads: true
theme: jekyll-theme-minimal
