title: Jimmy Mai
logo: /assets/headshot-circle.jpg
description: Data Science Enthusiast Seeking An Internship or Full-Time Opportunity| MS Business Analytics Student @ UT Dallas
show_downloads: true
theme: jekyll-theme-minimal
